server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:8060 #localhost a çekmeyi unutma
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth-service

        - id: user-profile-service
          predicates:
            - Path=/user-profile/**
          uri: http://localhost:8090
          #        - id: user-profile-service-follow
          #          predicates:
          #            - Path=/follow/**
          #          uri: http://localhost:8090
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user-profile-service

        - id: company-service
          predicates:
            - Path=/company/**
          uri: http://localhost:8070
        - id: comment-service
          predicates:
            - Path=/comment/**
          uri: http://localhost:8070
        - id: company-manager-service
          predicates:
            - Path=/company-manager/**
          uri: http://localhost:8070
        - id: company-profit-service
          predicates:
            - Path=/company-profit/**
          uri: http://localhost:8070
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/company-service

        - id: mail-service
          predicates:
            - Path=/mail/**
          uri: http://localhost:8080
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mail-service

      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}

          ## CircuitBreaker --> Bu bie devre kesicidir. Gateway e gelen isteklerde bir sorun olduğunda servisler için bir mesaj döner.
          # hataları tespit ederek devam etmemmelerini sağlar.
