server:
  port: 8070
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/WordGameGameDB
    username: postgres
    password: Bm15481527
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
