server:
  port: 8080
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  mail:
    username: ${mailadresi} # saved on env.
    password: ${mailsifrem} # saved on env.
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  mailQueue: mailQueue
  forgotPasswordQueue: forgot-password-queue
  user-mailQueue: user-mailQueue
  activateManagerQueue: activateManagerQueue