server:
  port: 8090
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: WordGameUserDB
      username: JavaUser
      password: root

jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}